import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AssistenteButton } from "@/components/customComponents/AssistentButton";
import Navbar from "@/components/logedComponents/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Stock Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} h-full antialiased`}
    >
      <Navbar />
      <AssistenteButton />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
