import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AssistentButton } from "@/components/logedComponents/AssistentButton";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Stock Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <AssistentButton />
        <Toaster position="top-center" /> 
      </body>
    </html>
  );
}
